const { contextBridge, ipcRenderer, webUtils } = require('electron');
const calls = ['init', 'answer', 'profile:save', 'folder:create', 'folder:rename', 'folder:delete', 'folder:export', 'profile:move', 'profile:secrets', 'profile:forget', 'profile:delete', 'config:export', 'config:import', 'settings:save', 'credentials:clear', 'snippets:save', 'terminal:open', 'terminal:activate', 'terminal:write', 'terminal:resize', 'terminal:close', 'terminal:log', 'graphics:open', 'graphics:activate', 'graphics:write', 'graphics:bounds', 'graphics:close', 'serial:list', 'clipboard:read', 'clipboard:write', 'select:folder', 'select:file', 'files:list', 'files:read', 'files:write', 'files:change', 'files:ftp', 'files:tightvnc', 'links:openProfile', 'files:tightClose', 'transfer:pick', 'zmodem:upload', 'zmodem:download', 'files:transfer', 'network:portscan', 'network:reachable', 'network:wol', 'links:open', 'import:scan', 'import:rdpFolder', 'import:apply', 'network:diagnostic', 'network:tunnel', 'network:serve', 'network:list', 'network:stop', 'tools:hash', 'tools:keygen', 'macros:save', 'scripts:save', 'lock:status', 'lock:set', 'lock:clear', 'lock:check', 'lock:autolock', 'session:saveOpen', 'session:loadOpen', 'history:load', 'history:save', 'sync:push', 'sync:pull', 'network:socks', 'network:remote', 'network:host', 'mirror:start', 'vnc:start', 'vnc:openViewer', 'packages:search', 'packages:installed', 'packages:upgrades', 'packages:operate', 'packages:cancel', 'packages:lists:save', 'packages:lists:export', 'packages:lists:import', 'tools:list', 'tools:install', 'tools:remove', 'transfer:add', 'transfer:folder', 'transfer:cancel', 'transfer:clear', 'transfer:list', 'network:filesOpen', 'tools:path', 'rdp:log', 'rdp:lastFailure', 'rdp:pickUpload', 'rdp:readChunk', 'rdp:saveDownload'];
const events = ['terminal:data', 'terminal:exit', 'graphics:data', 'graphics:state', 'question', 'notice', 'transfer:state', 'zmodem:progress', 'packages:log', 'network:reach'];
calls.push('import:file');
contextBridge.exposeInMainWorld('api', {
  pathFor: file => webUtils.getPathForFile(file),
  call: (channel, ...args) => { if (!calls.includes(channel)) throw new Error('Operação não permitida.'); return ipcRenderer.invoke(channel, ...args); },
  on: (channel, callback) => { if (!events.includes(channel)) throw new Error('Evento não permitido.'); const listener = (_, value) => callback(value); ipcRenderer.on(channel, listener); return () => ipcRenderer.removeListener(channel, listener); }
});
